# Generated by Django 6.1.1 on 2026-09-07 17:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(default='🍔', max_length=50, verbose_name='Ícono / Emoji')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Insumo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Insumo / Materia Prima')),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidades (u)'), ('KG', 'Kilogramos (kg)'), ('GRAMO', 'Gramos (g)'), ('LITRO', 'Litros (L)'), ('PORCION', 'Porciones')], default='UNIDAD', max_length=20, verbose_name='Unidad de Medida')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock Mínimo de Alerta')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo Unitario ($)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Insumo / Materia Prima',
                'verbose_name_plural': 'Insumos y Materias Primas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(max_length=30, unique=True, verbose_name='N° Ticket / Factura')),
                ('cliente_nombre', models.CharField(default='Consumidor Final', max_length=150, verbose_name='Nombre del Cliente')),
                ('cliente_identificacion', models.CharField(default='9999999999', max_length=20, verbose_name='RUC / Cédula')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', '💵 Efectivo'), ('TARJETA', '💳 Tarjeta de Débito/Crédito'), ('TRANSFERENCIA', '📱 Transferencia / QR')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago')),
                ('monto_recibido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Recibido ($)')),
                ('cambio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cambio ($)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal ($)')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IVA (15%) ($)')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total ($)')),
                ('estado', models.CharField(choices=[('COMPLETADA', '✅ Completada'), ('ANULADA', '❌ Anulada')], default='COMPLETADA', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones / Nota')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas Realizadas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Producto')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Venta ($)')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo Estimado ($)')),
                ('stock_disponible', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible (Unidades)')),
                ('stock_minimo', models.PositiveIntegerField(default=5, verbose_name='Stock Mínimo de Alerta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de Ingredientes / Combo')),
                ('emoji', models.CharField(default='🍔', max_length=50, verbose_name='Emoji Representativo')),
                ('activo', models.BooleanField(default=True, verbose_name='Disponible para Venta')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventory_sales.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto del Menú',
                'verbose_name_plural': 'Productos del Menú',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', '📥 Entrada / Reabastecimiento'), ('SALIDA_MERMA', '🗑️ Salida por Merma / Vencimiento'), ('AJUSTE', '⚖️ Ajuste Manual de Inventario')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Anterior')),
                ('stock_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Resultante')),
                ('motivo', models.TextField(verbose_name='Motivo / Justificación')),
                ('responsable', models.CharField(default='Admin', max_length=100, verbose_name='Responsable')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventory_sales.insumo', verbose_name='Insumo')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventory_sales.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario ($)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal ($)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalle', to='inventory_sales.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory_sales.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
